title: "Victor Ndayambaje"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
logo: /assets/img/IMG_5977.PNG

# Link to custom CSS
markdown: kramdown
sass:
  style: compressed
custom_css: /assets/css/custom.css
