title: "Victor Ndayambaje"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
logo: /assets/img/IMG_5977.PNG

# Custom assets
sass:
  style: compressed
assets:
  css:
    - /assets/css/custom.css
