title: "Victor Ndayambaje" # Your site title
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Custom assets for styling
sass:
  style: compressed

# Add your custom CSS file
assets:
  css:
    - /assets/css/custom.css

