title: Victor Ndayambaje # Your site title
logo: /assets/img/IMG_5977.PNG
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

# Custom assets for styling
sass:
  style: compressed

# Add your custom CSS file
assets:
  css:
    - /assets/css/custom.css

